### ISSUE TITLE
Live data stops being showed

### ISSUE THREAD

**Issue by wauterstoon** [grafana/mqtt-datasource#44] opened 2022-04-28 07:13 UTC
I have set up a Grafana local server v8.4.5 which is connected through an MQTT broker plugin for grafana which can be found here: [GitHub - grafana/mqtt-datasource: MQTT Datasource for Grafana allows streaming data from any MQTT broker running either locally or remotely. 1](https://github.com/grafana/mqtt-datasource) Succesfully installed that and works fine. The only problem i face is that my realtime data stops being showed after some minutes. I taught it was the auto refresh option but it wasn’t. Once i refresh the browser my live data is back and will be shown for another minute or two. I would like to have realtime data or data with 5-10 seconds delay.Does someone has any suggestions? Couldn’t find any thing on the forum.In the MQTT explorer application if see my realtime data so its very weird why it stops
![pEEEU](https://user-images.githubusercontent.com/64960215/165697389-29d184e1-6939-4ba4-a7f9-9404c4bcb439.png)
.

**Comment by Drakynn** [comment] 2022-05-21 13:04
You may want to post your log from the time period where the graph goes from properly displaying the data to stopping.

**Comment by santi-wg** [comment] 2022-05-23 09:09
I have the same problem
sorry for my english
When I use "1 data source" with 1 topic "no problem" ,
if "1 data source" with "2 topic" have a problem
and if I use 2 data source with 2 topic no problem
![Screenshot_2022-05-23_15-59-42](https://user-images.githubusercontent.com/88175726/169784540-ce936c73-e872-4219-b6b3-d419058375c1.png)
![Screenshot_2022-05-23_15-55-58](https://user-images.githubusercontent.com/88175726/169784585-c6457515-3310-4f38-95c5-753640c32a49.png)

Thanks
Sorry my english

**Comment by bmedici** [comment] 2022-12-07 20:09
Same here: data limited to "last 1m", when display graph flickers and stops. Eventually, it will start again streaming live data a few seconds/minutes later. 
Any idea ?

**Comment by ridomin** [comment] 2023-02-14 02:46
I also see this behavior with a single topic

**Comment by gpinkos** [comment] 2023-03-06 00:59
Readings are being sent through the broker about once every 3 seconds. Grafana displays 5 or 6 readings and then goes blank.  I confirmed that the readings are still being sent by the broker (they are visible in Node-RED and other apps).
![image](https://user-images.githubusercontent.com/97072938/222997076-b36caedb-6aab-4918-99c9-3c76e9507b14.png)

Same behavior for the Stat panel:
![image(1)](https://user-images.githubusercontent.com/97072938/222997095-a0120bae-14cc-49cb-b38c-4e916f15c514.png)

**Comment by VincentPapernest** [comment] 2023-03-16 09:05
Hi everyone ! I'm currently getting the same issue... Do you have some updates about it ?

**Comment by gdxas** [comment] 2023-03-20 10:24
We also experiencing the same issue in 9.4.1, looks like its fixed in 9.4.3

**Comment by Koivader** [comment] 2023-03-20 10:34
I’m using 9.4.3 and I still experience the issue

**Comment by gdxas** [comment] 2023-03-20 11:40
How long does it take for you before the issue occur for you?
For me it happened pretty fast in 9.4.1, but I have been running it for an hour+ without any issues in 9.4.3 now.

**Comment by Koivader** [comment] 2023-03-20 11:48
In my testing it only worked for about a minute. I don't know it it is a feature or a bug, but it looses its data if the timescale is changed. But sometimes changing the from eg 15min to 5 min made it work again.
For completeness, I'm using mosquitto in docker as broker with no TLS and no authentication.

**Comment by gdxas** [comment] 2023-03-20 14:21
OK. Here is the settins I use to make it work.

For the dashboard I run in now-5m with no refresh.
I set up all the widgets with MQTT, and then I restart the grafana service. 
After that it seams to run stable.

But if I change query options it will some times stop working again until i restart grafana service.

MQTT plugin is still in beta I see.

**Comment by Koivader** [comment] 2023-03-20 17:32
Thanks for the tip with the restart. Now it's working more reliable

**Comment by K3das** [comment] 2023-03-21 02:02
I've been getting this issue on 9.4.3, and for some reason it thinks that I'm no longer subscribed to it after ~15s, even though I am? 

```
logger=live.runstream t=2023-03-21T01:54:15.291216774Z level=debug msg="Stop stream since no active subscribers" channel=1/ds/OzkQYZf4z/1s/TestData/timeElapsed path=1s/TestData/timeElapsed
logger=live.runstream t=2023-03-21T01:54:15.291510139Z level=debug msg="Stream cleanly finished" path=1s/TestData/timeElapsed
logger=plugin.grafana-mqtt-datasource t=2023-03-21T01:54:15.291597254Z level=debug msg="stopped streaming (context canceled)" path=1s/TestData/timeElapsed
logger=plugin.grafana-mqtt-datasource t=2023-03-21T01:54:15.291625607Z level=debug msg="Unsubscribing from MQTT topic" topic=TestData/timeElapsed
```

Despite it thinking that I'm not subscribed it continues sending blank updates (`"data":{"values":[[],[]]}`) every second until the client actually sends an unsubscribe message

**Comment by gpinkos** [comment] 2023-03-21 20:17
I am still on OSS v9.4.3.  Per the suggestion  from @gdxas, I have set the time selector to 5 minutes with no refresh, and the MQTT streaming data is now working for more than 20 minutes (even though only 5 minutes are displayed on the graph).
![image](https://user-images.githubusercontent.com/97072938/226730576-478cf61c-84ec-4ffd-a9ca-38c3f58fa342.png)

**Comment by jasuade** [comment] 2023-03-30 09:38
Could be something as in [here](https://github.com/eclipse/paho.mqtt.golang/issues/69) the broker close old connection because the client id is same?

**Comment by peter9091** [comment] 2023-03-30 19:39
I have the same problem with Grafana 9.4.7 on Raspberry.
I started mosquitto_sub in another window, so i can see that the messages are still published, but MQTT Source stops after receiving a few messages, sometimes after a few minutes. 

In my case it's not because of the same client ID, I checked the logs and there is no "already connected" in mosquitto.log, that appears when I try to connect to mosquitto by mosquitto_sub using the same client ID as grafana MQTT source.

This seems to be a bug of this source.

**Comment by chefscho** [comment] 2023-03-31 11:52
Hi, 

after some more investigation my initial problem (not receiving any palyoads) was caused by the topic I was trying to subscribe to. 
Publishing - for testing purposes - on a topic without leading "/" is working. So far the stream is working - no outages until now. Will keep you guys updated.

**Comment by PiotrMarzecVSG** [comment] 2023-03-31 13:48
It seems it is somehow related to a selected time range - not on the dashboard only but also when using Data Source Explore functionality. Whenever I change the time range data reappears.

**Comment by PiotrMarzecVSG** [comment] 2023-03-31 13:59
Looks like it is somehow related to the selected time range - both on the dashboard and Data Source Explore functionality. Whenever data stops, I change the time range and data is being visible and updated again. **Refreshing dashboard and cancelling/run query does not help.**

**Comment by Neumi** [comment] 2023-04-12 12:28
> OK. Here is the settins I use to make it work.
> 
> For the dashboard I run in now-5m with no refresh. I set up all the widgets with MQTT, and then I restart the grafana service. After that it seams to run stable.
> 
> But if I change query options it will some times stop working again until i restart grafana service.
> 
> MQTT plugin is still in beta I see.

I can confirm that this method works for me as well!

**Comment by wemod123** [comment] 2023-04-13 09:34
> However, looks like it is somehow related to the selected time range - both on the dashboard and Data Source Explore functionality. Whenever data stops, I change the time range and data is being visible and updated again. Refreshing the dashboard, refreshing the browser, restarting the broker and cancelling/run query (in Data Source Explore) do not help **but changing time range always helps** - still temporarily though.

Exactly what I am experiencing now

**Comment by PiotrMarzecVSG** [comment] 2023-04-20 07:09
In the plugin's code there is some logging included. How can I read the logs? Maybe there is some information related to this issue there?

**Comment by mike006322** [comment] 2023-05-04 19:19
I'm experiencing the same issue. 

MQTT logs say that Grafana MQTT client unsubscribed from the topic. 

Only unsubscribe invocations in source code are in pkg/stream.go on lines 27 and 35.

**Comment by isarantidis** [comment] 2023-05-09 13:38
The plugin registers requests for MQTT topic data in a map with key format "<INTERVAL>/<MQTT_TOPIC>". This is derived from the Grafana Live channel e.g. _ds/be19d38d-2126-430f-95b1-d2eebd9ef710/500ms/MQTT_TOPIC_A_.  Some times due to events coming from the UI (not sure which the full set of those cases is), the panels subscribe to a different Grafana Live channel, where the interval is different e.g.  _ds/be19d38d-2126-430f-95b1-d2eebd9ef710/1000ms/MQTT_TOPIC_A_.

The problem is that the plugin's backend code as it is, will insert into a map the new "requests for data" with key **_1000ms/MQTT_TOPIC_A_** but then it will remove from the map the previous entry **_500ms/MQTT_TOPIC_A_** and cancel the subscription to **MQTT_TOPIC_A**. Therefore the subscribers with key **_1000ms/MQTT_TOPIC_A_** will not receive any data and therefore neither will the panels.

I have modified the backend code in my repository fork, in order to not cancel the subscription to MQTT topic if there is at least on other "request for data" from it. I built the plugin and the problem is solved for me at least.

**Comment by lzaugg** [comment] 2023-05-23 09:39
Thanks @isarantidis for analysing and providing a fix for (parts of) this issue. Works much more reliable on our end with the patch. Hope someone will review the PR https://github.com/grafana/mqtt-datasource/pull/76 soon.

**Comment by JohanScheepers** [comment] 2023-06-28 11:22
Also exercising stability issues.

Grafana v10.0

**Comment by goerdi** [comment] 2023-06-30 11:42
10.1 the same....

**Comment by effgee** [comment] 2023-07-15 07:00
Still happening Grafana v10.0.2-cloud
Haven't tried implementing isarantidis's fix, but not sure how I'd do that with the cloud version anyway

**Comment by KhurramFHassan** [comment] 2023-08-12 12:44
I have the same problem on grafana version 10.0.3 running on Ubuntu on a raspberry pi 4. Can someone please post instructions on compiling the mqtt plugin incorporating @isarantidis patch?

**Comment by patsuhiko** [comment] 2023-08-12 19:56
Same here, activated two queries then the data will sometimes show up with the correct values and then the stat visu will display "No data", but the data is there when i check it with MQTT explorer.

**Closed** 2023-08-17 17:28 UTC

**Comment by toddtreece** [comment] 2023-08-17 20:34
`v1.0.0-beta.3` has been released with the fix from #84

**Comment by stenfalp** [comment] 2023-10-23 08:56
I have the same problem with v1.0.0-beta.3. It only works with 5mins no refresh, but on the same dashboard I have visualizations that require 24h of data, so it is not a solution for me.

**Comment by GalamexMc** [comment] 2024-05-30 13:13
Has anyone been able to find a solution to this issue for Grafana Cloud? Thanks.

**Comment by frankvandenhurk** [comment] 2024-06-12 17:42
> I have the same problem with v1.0.0-beta.3. It only works with 5mins no refresh, but on the same dashboard I have visualizations that require 24h of data, so it is not a solution for me. (Grafana 10.1.2 on RPi 3B+)

Same for me

**Comment by wavelov3r** [comment] 2024-09-02 17:36
![Image](https://github.com/user-attachments/assets/4aecbcb2-c959-44e0-a5c7-e25367c699be)

No way. MQTT Topics are listed in mqtt explorer.
Grafana version: 10.0.0
MQTT plugin: 1.1.0-beta.2

**Comment by ParttyMaker** [comment] 2024-12-11 20:38
> ![Image](https://github.com/user-attachments/assets/4aecbcb2-c959-44e0-a5c7-e25367c699be)
> 
> No way (with or withouth starting/ending slashes, and restricted to 1 m); never worked for me. MQTT Topics are listed in mqtt explorer. Grafana version: 10.0.0 MQTT plugin: 1.1.0-beta.2
> 
> edit: Mosquitto log: 2024-09-02 18:51:36: New connection from 10.1.1.4:60763 on port 1883. 2024-09-02 18:51:36: New client connected from 10.1.1.4:60763 as mqtt-explorer-8e3738be (p2, c1, k60, u'mREDACTEDer'). 2024-09-02 18:51:53: New connection from 172.30.32.2:40600 on port 1883. 2024-09-02 18:51:53: Client closed its connection. 2024-09-02 18:53:53: New connection from 172.30.32.2:52352 on port 1883. 2024-09-02 18:53:53: Client closed its connection. 2024-09-02 18:55:53: New connection from 172.30.32.2:44788 on port 1883. 2024-09-02 18:55:53: Client closed its connection. 2024-09-02 18:57:27: Saving in-memory database to /data//mosquitto.db. 2024-09-02 18:57:53: New connection from 172.30.32.2:58220 on port 1883. 2024-09-02 18:57:53: Client closed its connection. 2024-09-02 18:59:49: New connection from 172.30.32.1:56088 on port 1883. 2024-09-02 18:59:49: New client connected from 172.30.32.1:56088 as grafana_5586540353105740914 (p2, c1, k60, u'mREDACTEDr'). 2024-09-02 18:59:53: New connection from 172.30.32.2:46470 on port 1883. 2024-09-02 18:59:53: Client closed its connection. 2024-09-02 18:59:54: Client grafana_2002857865777582447 disconnected. 2024-09-02 19:01:53: New connection from 172.30.32.2:58686 on port 1883. 2024-09-02 19:01:53: Client closed its connection. 2024-09-02 19:03:53: New connection from 172.30.32.2:60646 on port 1883. 2024-09-02 19:03:53: Client closed its connection. 2024-09-02 19:05:53: New connection from 172.30.32.2:40954 on port 1883. 2024-09-02 19:05:53: Client closed its connection. 2024-09-02 19:07:53: New connection from 172.30.32.2:57000 on port 1883. 2024-09-02 19:07:53: Client closed its connection.

have you find a solution?
